name: care_shield
description: CareShield - Confidential HIV health delivery prototype (Flutter)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  # State management
  provider: ^6.0.6

  # Local encrypted storage
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  # Fonts & icons
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.0

  # Utilities
  crypto: ^3.0.2
  uuid: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_placeholder.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_placeholder.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_placeholder.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_placeholder.png"
    icon_size: 48 # min:48, max:256, default: 48
