services:
  backend:
    build: .
    ports:
      - "3000:3000"
    # Load environment from host .env so Prisma uses Render Postgres
    env_file:
      - .env
    environment:
      # Allow overriding or ensuring vars are present; fallback provided for JWT_SECRET only
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_DIRECT_URL=${DATABASE_DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
